name: env
channels:
  - pytorch
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _py-xgboost-mutex=2.0
  - anyio=4.9.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.3
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - comm=0.2.2
  - contourpy=1.3.1
  - cpython=3.10.16
  - cycler=0.12.1
  - debugpy=1.8.11
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.18.0
  - fonttools=4.57.0
  - fqdn=1.5.1
  - freetype=2.13.3
  - fsspec=2025.3.2
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - h11=0.14.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.10
  - imbalanced-learn=0.13.0
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.35.0
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - json5=0.12.0
  - jsonpointer=2.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.6
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250127.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=20.1.2
  - libdeflate=1.23
  - libedit=3.1.20191231
  - libffi=3.4.4
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libopenblas=0.3.24
  - libpng=1.6.47
  - libprotobuf=5.29.3
  - libsodium=1.0.20
  - libsqlite=3.45.2
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libuv=1.50.0
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxgboost=2.1.4
  - libzlib=1.3.1
  - llvm-openmp=20.1.2
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=1.0
  - notebook=7.3.3
  - notebook-shim=0.2.4
  - numpy=2.2.4
  - openjpeg=2.5.3
  - openssl=3.4.1
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.7
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-xgboost=2.1.4
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pygments=2.19.1
  - pyobjc-core=10.1
  - pyobjc-framework-cocoa=10.1
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytorch=2.5.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - send2trash=1.8.3
  - setuptools=75.8.0
  - six=1.17.0
  - sklearn-compat=0.1.3
  - sleef=3.8
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.45.2
  - stack_data=0.6.3
  - sympy=1.13.3
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.13.1
  - typing_extensions=4.13.1
  - typing_utils=0.1.0
  - tzdata=2025a
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xgboost=2.1.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - import-ipynb==0.2
prefix: /opt/anaconda3/envs/env
